import * as polygonClipping from 'polygon-clipping';
import {multiPolygonArea,offsetWater,polygonArea,type MultiPolygonMm,type PolygonMm,type RingMm} from './polygonEngine';
export const NORMALIZED_DESIGN_WIDTH=500;
export type ArtisticDepthPresetName='xfine'|'fine'|'narrow'|'normal'|'wide'|'custom';
export type ArtisticDepthPreset={name:ArtisticDepthPresetName;normalizedOffsets:number[];measured:boolean};
export const ARTISTIC_DEPTH_PRESETS:Record<Exclude<ArtisticDepthPresetName,'custom'>,ArtisticDepthPreset>={
 xfine:{name:'xfine',normalizedOffsets:[1,3,7,12,19],measured:false},fine:{name:'fine',normalizedOffsets:[2,6,13,22,34],measured:false},narrow:{name:'narrow',normalizedOffsets:[2.5,7.5,16,27,41],measured:false},normal:{name:'normal',normalizedOffsets:[3,9,20,34,52],measured:true},wide:{name:'wide',normalizedOffsets:[5,14,30,49,73],measured:false},
};
export type ArtisticDepthCleanup={preOffsetSimplifyTolerance:number;postOffsetSimplifyTolerance:number;minimumComponentAreaNormalized:number[];minimumComponentAreaRatio:number[];minimumHoleAreaNormalized:number[];cropEdgeMinimumAreaNormalized:number};
export const DEFAULT_ARTISTIC_DEPTH_CLEANUP:ArtisticDepthCleanup={preOffsetSimplifyTolerance:.08,postOffsetSimplifyTolerance:.04,minimumComponentAreaNormalized:[.5,1,2,3,4],minimumComponentAreaRatio:[.001,.003,.01,.015,.02],minimumHoleAreaNormalized:[.2,.5,1,1.5,2],cropEdgeMinimumAreaNormalized:.25};
export const normalizedProductSize=(widthMm:number,heightMm:number)=>({width:500,height:500*heightMm/widthMm});
export const normalizedOffsetToMm=(normalizedOffset:number,widthMm:number)=>normalizedOffset*widthMm/NORMALIZED_DESIGN_WIDTH;
export function presetOffsets(name:ArtisticDepthPresetName,custom:number[]=[]){return name==='custom'?custom:[...ARTISTIC_DEPTH_PRESETS[name].normalizedOffsets]}
const sq=(value:number)=>value*value;
const pointSegmentDistanceSq=(p:[number,number],a:[number,number],b:[number,number])=>{const dx=b[0]-a[0],dy=b[1]-a[1];if(dx===0&&dy===0)return sq(p[0]-a[0])+sq(p[1]-a[1]);const t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy))),x=a[0]+t*dx,y=a[1]+t*dy;return sq(p[0]-x)+sq(p[1]-y)};
function simplifyOpen(points:[number,number][],tolerance:number):[number,number][]{if(points.length<=2)return points;let max=0,index=0;for(let i=1;i<points.length-1;i++){const distance=pointSegmentDistanceSq(points[i],points[0],points.at(-1)!);if(distance>max){max=distance;index=i}}if(max>tolerance*tolerance){const left=simplifyOpen(points.slice(0,index+1),tolerance),right=simplifyOpen(points.slice(index),tolerance);return[...left.slice(0,-1),...right]}return[points[0],points.at(-1)!]}
function simplifyRing(ring:RingMm,toleranceMm:number):RingMm{if(toleranceMm<=0)return ring;const points=ring.slice(0,-1);if(points.length<4)return ring;let farthest=1,max=0;for(let i=1;i<points.length;i++){const distance=sq(points[i][0]-points[0][0])+sq(points[i][1]-points[0][1]);if(distance>max){max=distance;farthest=i}}const rotated=[...points.slice(farthest),...points.slice(0,farthest),points[farthest]],simplified=simplifyOpen(rotated,toleranceMm);if(simplified.length<4)return ring;return simplified}
function simplifyGeometry(geometry:MultiPolygonMm,toleranceMm:number):MultiPolygonMm{return geometry.map(polygon=>polygon.map(ring=>simplifyRing(ring,toleranceMm))).filter(polygon=>polygon.length&&polygonArea(polygon)>0)}
const ringArea=(ring:RingMm)=>Math.abs(ring.slice(0,-1).reduce((sum,p,index)=>{const q=ring[index+1];return sum+p[0]*q[1]-q[0]*p[1]},0)/2);
const touchesCrop=(polygon:PolygonMm,width:number,height:number,epsilon=.002)=>polygon[0].some(([x,y])=>x<=epsilon||y<=epsilon||x>=width-epsilon||y>=height-epsilon);
const depthValue=(values:number[],index:number)=>values[Math.min(index,values.length-1)];
export type ArtisticOpening={normalizedOffset:number;physicalOffsetMm:number;geometry:MultiPolygonMm;areaMm2:number;componentCount:number;holeCount:number;vertexCount:number;smallestComponentAreaMm2:number;largestComponentAreaMm2:number;rejectedComponents:number;rejectedHoles:number};
export function artisticDepthOpenings(original:MultiPolygonMm,normalizedOffsets:number[],widthMm:number,heightMm:number,minComponentAreaNormalized?:number,cleanup:ArtisticDepthCleanup=DEFAULT_ARTISTIC_DEPTH_CLEANUP):ArtisticOpening[]{
 const scale=widthMm/NORMALIZED_DESIGN_WIDTH,working=simplifyGeometry(original,cleanup.preOffsetSimplifyTolerance*scale),originalArea=multiPolygonArea(original);
 return normalizedOffsets.map((normalizedOffset,depthIndex)=>{const physicalOffsetMm=normalizedOffsetToMm(normalizedOffset,widthMm),minimumHoleArea=depthValue(cleanup.minimumHoleAreaNormalized,depthIndex)*scale*scale;let rejectedHoles=0;const depthWorking=working.map(polygon=>[polygon[0],...polygon.slice(1).filter(hole=>{const keep=ringArea(hole)>=minimumHoleArea;if(!keep)rejectedHoles++;return keep})]);let eroded:MultiPolygonMm=[];try{eroded=offsetWater(depthWorking,-physicalOffsetMm,widthMm,heightMm)}catch(error){if(!(error as Error).message.includes('collapsed'))throw error}eroded=simplifyGeometry(eroded,cleanup.postOffsetSimplifyTolerance*scale);try{eroded=polygonClipping.intersection(eroded,original)}catch(error){throw new Error(`Artistic depth topology repair failed: ${(error as Error).message}`)}const largestArea=Math.max(0,...eroded.map(polygonArea)),absoluteNormalized=minComponentAreaNormalized??depthValue(cleanup.minimumComponentAreaNormalized,depthIndex),absoluteArea=absoluteNormalized*scale*scale,relative=depthValue(cleanup.minimumComponentAreaRatio,depthIndex),edgeArea=cleanup.cropEdgeMinimumAreaNormalized*scale*scale;let rejectedComponents=0;const cleaned=eroded.filter(polygon=>{const area=polygonArea(polygon),keep=area===largestArea||(touchesCrop(polygon,widthMm,heightMm,physicalOffsetMm+.002)?area>=edgeArea:area>=absoluteArea&&area>=largestArea*relative&&area>=originalArea*relative*.25);if(!keep)rejectedComponents++;return keep}).map(polygon=>{const holes=polygon.slice(1).filter(hole=>{const keep=ringArea(hole)>=minimumHoleArea;if(!keep)rejectedHoles++;return keep});return[polygon[0],...holes]});const areas=cleaned.map(polygonArea),holeCount=cleaned.reduce((sum,polygon)=>sum+polygon.length-1,0),vertexCount=cleaned.reduce((sum,polygon)=>sum+polygon.reduce((ringSum,ring)=>ringSum+ring.length-1,0),0);return{normalizedOffset,physicalOffsetMm,geometry:cleaned,areaMm2:multiPolygonArea(cleaned),componentCount:cleaned.length,holeCount,vertexCount,smallestComponentAreaMm2:areas.length?Math.min(...areas):0,largestComponentAreaMm2:areas.length?Math.max(...areas):0,rejectedComponents,rejectedHoles}});
}
