import type {BathymetryContour,BathymetryDataset,BathymetrySourceMetadata,GeoPolygon} from '../types/project';
// [lng,lat] positions, polygon-clipping's MultiPolygon layout.
export type GeoMultiPolygon=[number,number][][][];
// water: the selected water body (the shoreline the panels are cut from), in lng/lat. Providers
// match surveyed lakes against it spatially and route by the state it lies in; longitude/latitude
// is a point inside it when it is known.
export type BathymetryQuery={longitude:number;latitude:number;waterbodyName?:string;waterbodyId?:string;water?:GeoMultiPolygon};
// provider 'none': no agency was asked (e.g. the lake is outside every supported state).
export type BathymetryProviderResult={provider:BathymetrySourceMetadata['provider']|'none';status:'available'|'unavailable'|'unsupported';message:string;dataset?:BathymetryDataset;sourceUrl?:string;waterbodyId?:string};
export interface BathymetryProvider{id:string;label:string;resolve(query:BathymetryQuery):Promise<BathymetryProviderResult>}
export interface BathymetryCache{get(key:string):Promise<BathymetryProviderResult|undefined>;set(key:string,value:BathymetryProviderResult):Promise<void>}
export const feetToMeters=(feet:number)=>feet*0.3048;
export const normalizeDepth=(value:number,unit:string)=>{if(!Number.isFinite(value)||value<0)throw new Error('Depth values must be finite and non-negative.');if(/^m(eters?)?$/i.test(unit))return value;if(/^(ft|feet|foot)$/i.test(unit))return feetToMeters(value);throw new Error(`Unsupported or missing depth unit: ${unit||'(missing)'}`)};
export const validateDataset=(dataset:BathymetryDataset)=>{if(!dataset.contours.length)throw new Error('Bathymetry dataset contains no depth-region polygons.');let previous=-Infinity;for(const contour of [...dataset.contours].sort((a,b)=>a.depthMeters-b.depthMeters)){if(contour.depthMeters<=previous||!contour.geometry.length)throw new Error('Bathymetry contours require unique increasing depths and polygon geometry.');previous=contour.depthMeters}return dataset};
export function automaticThresholds(contours:BathymetryContour[],count:number){const depths=[...new Set(contours.map(c=>c.depthMeters))].sort((a,b)=>a-b);if(count<=0)return[];if(depths.length<count)throw new Error(`Bathymetry has only ${depths.length} usable depth levels for ${count} enabled depth panels.`);return Array.from({length:count},(_,i)=>depths[Math.round(i*(depths.length-1)/Math.max(1,count-1))])}
export const sourceMetadata=(source:Omit<BathymetrySourceMetadata,'notForNavigation'>):BathymetrySourceMetadata=>({...source,notForNavigation:true});
export type GeoJsonFeature={type:'Feature';properties:Record<string,unknown>;geometry:{type:'Polygon'|'MultiPolygon';coordinates:any}};
const geoPolygon=(coordinates:number[][][],id:string):GeoPolygon=>({id,rings:coordinates.map(ring=>ring.map(([lng,lat])=>({lng,lat})))});
export function importDepthRegionGeoJson(input:unknown,fileName='bathymetry.geojson'):BathymetryDataset{const root=input as any,features:GeoJsonFeature[]=root?.type==='FeatureCollection'?root.features:root?.type==='Feature'?[root]:[];if(!features.length)throw new Error('Expected a GeoJSON FeatureCollection of Polygon or MultiPolygon depth regions.');const byDepth=new Map<number,GeoPolygon[]>(),units=new Set<string>();for(const[featureIndex,feature]of features.entries()){const unit=String(feature.properties.depth_unit??feature.properties.unit??'');units.add(unit);const depth=normalizeDepth(Number(feature.properties.depth??feature.properties.depth_value),unit),polygons=feature.geometry?.type==='Polygon'?[feature.geometry.coordinates]:feature.geometry?.type==='MultiPolygon'?feature.geometry.coordinates:undefined;if(!polygons)throw new Error('Bathymetry GeoJSON supports Polygon and MultiPolygon depth regions only.');byDepth.set(depth,[...(byDepth.get(depth)??[]),...polygons.map((polygon:number[][][],index:number)=>geoPolygon(polygon,`import-${featureIndex}-${index}`))])}const contours=[...byDepth].sort(([a],[b])=>a-b).map(([depthMeters,geometry])=>({depthMeters,geometry})),depths=contours.map(c=>c.depthMeters);return validateDataset({source:sourceMetadata({provider:'user',datasetId:`user:${fileName}`,title:fileName,retrievedAt:new Date().toISOString(),quality:'User-supplied georeferenced depth-region polygons; verify source accuracy.'}),depthUnit:'meters',minDepthMeters:Math.min(...depths),maxDepthMeters:Math.max(...depths),contours})}
