import type {BathymetryProvider,BathymetryProviderResult,BathymetryQuery} from './model';

export class WisconsinDnrProvider implements BathymetryProvider{
 id='wisconsin-dnr';label='Wisconsin DNR';
 constructor(private fetcher:typeof fetch=(input,init)=>globalThis.fetch(input,init)){}
 async resolve(query:BathymetryQuery):Promise<BathymetryProviderResult>{
  const params=new URLSearchParams({f:'json',geometry:`${query.longitude},${query.latitude}`,geometryType:'esriGeometryPoint',inSR:'4326',spatialRel:'esriSpatialRelIntersects',distance:'5000',units:'esriSRUnit_Meter',outFields:'WATERBODY_NAME,WATERBODY_WBIC',returnGeometry:'false'}),url=`https://dnrmaps.wi.gov/arcgis/rest/services/ER_Biotics/ER_Biotics_WGS84_Hydro/MapServer/0/query?${params}`;
  try{const response=await this.fetcher(url);if(!response.ok)throw new Error(`HTTP ${response.status}`);const json=await response.json(),features=json.features??[],words=(value:string)=>new Set(value.toLowerCase().match(/[a-z]+/g)?.filter(word=>!['lake','reservoir','wisconsin','the'].includes(word))??[]),wanted=words(query.waterbodyName??''),rank=(feature:any)=>[...words(String(feature.attributes?.WATERBODY_NAME??''))].filter(word=>wanted.has(word)).length,attributes=[...features].sort((a,b)=>rank(b)-rank(a))[0]?.attributes;if(!attributes||query.waterbodyName&&rank({attributes})===0)return{provider:'wisconsin-dnr',status:'unavailable',message:'Wisconsin DNR hydrography found no matching lake within 5 km of the selected point.'};const wbic=String(attributes.WATERBODY_WBIC),sourceUrl=`https://apps.dnr.wi.gov/lakes/lakepages/LakeDetail.aspx?page=facts&wbic=${wbic}`;return{provider:'wisconsin-dnr',status:'unsupported',waterbodyId:wbic,sourceUrl,message:`Wisconsin DNR identifies ${attributes.WATERBODY_NAME??'this waterbody'} (WBIC ${wbic}). DNR contour maps may be scanned historical documents; no verified georeferenced depth polygons were returned automatically.`}}catch(error){return{provider:'wisconsin-dnr',status:'unavailable',message:`Wisconsin DNR provider unavailable: ${(error as Error).message}`}}
 }
}
export class NoaaNceiProvider implements BathymetryProvider{id='noaa-ncei';label='NOAA/NCEI';async resolve():Promise<BathymetryProviderResult>{return{provider:'noaa-ncei',status:'unsupported',sourceUrl:'https://www.ncei.noaa.gov/products/great-lakes-bathymetry',message:'NOAA/NCEI machine-readable contours and grids currently cover the Great Lakes, not generic Wisconsin inland lakes.'}}}
export class UsgsProvider implements BathymetryProvider{id='usgs';label='USGS';async resolve():Promise<BathymetryProviderResult>{return{provider:'usgs',status:'unsupported',sourceUrl:'https://www.usgs.gov/3d-elevation-program/inland-bathymetry',message:'USGS inland bathymetry is survey-specific. Automatic inventory footprint ingestion is not yet implemented.'}}}
