import {useState} from 'react';
import type {ManufacturingScene} from '../../export/scene';
import {scenePreviewSvg,type PreviewMode} from '../../export/svg/previewSvg';

export function GeneratedPreview({scene,featuresLoaded=false}:{scene?:ManufacturingScene;featuresLoaded?:boolean}){
 const[view,setView]=useState<PreviewMode>('individual'),[layer,setLayer]=useState(0);
 if(!scene)return <div className="empty"><b>GENERATED MAP MODE</b><p>{featuresLoaded?'Vector features loaded. Click Generate scene to build the manufacturing preview.':'Load vector features, then generate the manufacturing scene.'}</p></div>;
 const selected=Math.min(layer,scene.layers.length-1),svg=scenePreviewSvg(scene,view,selected),m=scene.geometryMetrics;
 return <div className="generated"><div className="mode-badge generated-badge">GENERATED MAP MODE</div><div className="preview-controls"><button className={view==='individual'?'active':''} onClick={()=>setView('individual')}>Individual Layer</button><button className={view==='composite'?'active':''} onClick={()=>setView('composite')}>Composite</button><button className={view==='exploded'?'active':''} onClick={()=>setView('exploded')}>Exploded</button>{view==='individual'&&<select value={selected} onChange={e=>setLayer(+e.target.value)}>{scene.layers.map((item,index)=><option value={index} key={item.id}>{item.name}</option>)}</select>}</div><div className="size-readout">{scene.widthMm.toFixed(3)} × {scene.heightMm.toFixed(3)} mm · {scene.layers.length} panels</div><div className="svg-preview" data-preview-mode={view} dangerouslySetInnerHTML={{__html:svg}}/>{m&&<details className="geometry-metrics"><summary>Geometry metrics</summary>{m.normalizedProductSize&&<span>Normalized product: {m.normalizedProductSize.width.toFixed(0)} × {m.normalizedProductSize.height.toFixed(1)}</span>}<span>Raw water features: {m.rawWaterFeatures}</span><span>Normalized polygon components: {m.normalizedPolygonComponents}</span><span>Unioned components: {m.unionedComponents}</span><span>Selected water components: {m.selectedWaterComponents}</span><span>Original water area: {m.originalWaterAreaMm2.toFixed(1)} mm²</span>{m.openingAreasMm2.map((area,index)=><span key={index}>Opening {index+1}{m.artisticOffsetsNormalized?.[index-1]!=null?` · inset ${m.artisticOffsetsNormalized[index-1]}u`:''}: {area.toFixed(1)} mm²</span>)}<span>Invalid/rejected rings: {m.invalidRejectedRings}</span>{m.artisticOpenings?.map((opening,index)=><span key={`metric-${index}`}>W{index+1}: {opening.components} components · {opening.holes} holes · {opening.vertices} vertices · rejected {opening.rejectedComponents} components/{opening.rejectedHoles} holes</span>)}{m.rejectedArtisticComponents!=null&&<span>Rejected artistic components: {m.rejectedArtisticComponents}</span>}{m.rejectedArtisticHoles!=null&&<span>Rejected artistic holes: {m.rejectedArtisticHoles}</span>}</details>}</div>;
}
