import {useState} from 'react';
import type {GeocoderResult} from '../../map/geocoding/GeocoderService';
import {PhotonGeocoder} from '../../map/geocoding/GeocoderService';
import type {MapProject} from '../../types/project';
import {inchesToMm,mmToInches,validateDimensionMm} from '../../utils/units';
import {importDepthRegionGeoJson} from '../../bathymetry/model';
import {BathymetryResolver,LocalStorageBathymetryCache} from '../../bathymetry/resolver';
import {NoaaNceiProvider,UsgsProvider,WisconsinDnrProvider} from '../../bathymetry/providers';
import {ARTISTIC_DEPTH_PRESETS,type ArtisticDepthPresetName} from '../../geometry/shoreline/artisticDepth';
const sections=['Map View','Road Labels','Place Labels','Title / Subtitle','Preview'] as const;
export function Controls({project,setProject,onSelect,onGenerate,onExport,status,counts}:{project:MapProject;setProject:(p:MapProject)=>void;onSelect:(r:GeocoderResult)=>void;onGenerate:()=>void;onExport:()=>void;status:string;counts:{water:number;roads:number;namedRoads:number;places:number}}){const[q,setQ]=useState('Caldron Falls, Wisconsin'),[results,setResults]=useState<GeocoderResult[]>([]),[error,setError]=useState(''),[searching,setSearching]=useState(false),[checkingDepth,setCheckingDepth]=useState(false);const patch=(x:Partial<MapProject>)=>setProject({...project,...x});const search=async()=>{setSearching(true);setError('');try{const r=await new PhotonGeocoder().search(q);setResults(r);if(!r.length)setError('No search results found')}catch(e){setError((e as Error).message)}finally{setSearching(false)}};
 const dim=(key:'widthMm'|'heightMm',raw:number)=>{const mm=project.dimensions.displayUnit==='in'?inchesToMm(raw):raw;if(validateDimensionMm(mm))patch({dimensions:{...project.dimensions,[key]:mm}})};
 const checkBathymetry=async()=>{setCheckingDepth(true);const resolver=new BathymetryResolver([new WisconsinDnrProvider(),new NoaaNceiProvider(),new UsgsProvider()],new LocalStorageBathymetryCache('lms:bathymetry:v2:'));try{const found=await resolver.resolve({longitude:project.map.longitude,latitude:project.map.latitude,waterbodyName:q}),result=found.find(item=>item.status==='available')??found[0],available=result.status==='available';patch({bathymetry:{...project.bathymetry,mode:available?'true-bathymetry':project.bathymetry.mode,provider:result.provider,status:available?'available':'unavailable',statusMessage:result.message,dataset:result.dataset,datasetId:result.dataset?.source.datasetId}})}finally{setCheckingDepth(false)}};
 const importBathymetry=async(file?:File)=>{if(!file)return;try{const dataset=importDepthRegionGeoJson(JSON.parse(await file.text()),file.name);patch({bathymetry:{...project.bathymetry,mode:'true-bathymetry',provider:'user',datasetId:dataset.source.datasetId,dataset,status:'available',statusMessage:`Loaded ${dataset.contours.length} verified depth-region levels from ${file.name}.`,thresholdsMeters:[]}})}catch(reason){patch({bathymetry:{...project.bathymetry,status:'error',statusMessage:(reason as Error).message}})}};
 const bathymetryDataset=project.bathymetry.dataset;
 return <aside><h1>Layered Map Studio</h1><details open><summary>1. Location</summary><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()}/><button onClick={search} disabled={searching}>{searching?'Searching…':'Search'}</button>{error&&<p className="error">{error}</p>}<div className="results">{results.map(r=><button key={r.id} onClick={()=>onSelect(r)}>{r.displayName}</button>)}</div></details>
 <details open><summary>2. Physical Size</summary><label>Units <select value={project.dimensions.displayUnit} onChange={e=>patch({dimensions:{...project.dimensions,displayUnit:e.target.value as 'in'|'mm'}})}><option value="in">Inches</option><option value="mm">Millimeters</option></select></label><label>Width <input type="number" step="0.1" value={project.dimensions.displayUnit==='in'?mmToInches(project.dimensions.widthMm):project.dimensions.widthMm} onChange={e=>dim('widthMm',+e.target.value)}/></label><label>Height <input type="number" step="0.1" value={project.dimensions.displayUnit==='in'?mmToInches(project.dimensions.heightMm):project.dimensions.heightMm} onChange={e=>dim('heightMm',+e.target.value)}/></label><small>{project.dimensions.widthMm.toFixed(3)} × {project.dimensions.heightMm.toFixed(3)} mm</small></details>
 <details open><summary>3. Depth Data</summary><label>Mode <select value={project.bathymetry.mode} onChange={e=>patch({bathymetry:{...project.bathymetry,mode:e.target.value as MapProject['bathymetry']['mode']}})}><option value="true-bathymetry">True Bathymetry</option><option value="decorative-offsets">Artistic Depth</option></select></label><button onClick={checkBathymetry} disabled={checkingDepth}>{checkingDepth?'Checking providers…':'Check Bathymetry'}</button><label>Import depth-region GeoJSON <input type="file" accept=".geojson,.json,application/geo+json,application/json" onChange={e=>importBathymetry(e.target.files?.[0])}/></label><small>{project.bathymetry.statusMessage??'Bathymetry has not been checked. Artistic Depth is shoreline-derived, not surveyed depth.'}</small>{bathymetryDataset&&<><label>Thresholds <select value={project.bathymetry.selection} onChange={e=>patch({bathymetry:{...project.bathymetry,selection:e.target.value as 'automatic'|'manual'}})}><option value="automatic">Automatic</option><option value="manual">Manual</option></select></label><small>Range: {(bathymetryDataset.minDepthMeters/0.3048).toFixed(1)}–{(bathymetryDataset.maxDepthMeters/0.3048).toFixed(1)} ft · {bathymetryDataset.source.title} · NOT FOR NAVIGATION</small>{project.bathymetry.selection==='manual'&&[1,2,3,4,5].filter(i=>project.shoreline.enabledLayers[i]).map((_,position)=><label key={position}>Depth layer {position+1}<select value={project.bathymetry.thresholdsMeters[position]??bathymetryDataset.contours[position]?.depthMeters} onChange={e=>{const values=[...project.bathymetry.thresholdsMeters];values[position]=+e.target.value;patch({bathymetry:{...project.bathymetry,thresholdsMeters:values}})}}>{bathymetryDataset.contours.map(contour=><option key={contour.depthMeters} value={contour.depthMeters}>{(contour.depthMeters/0.3048).toFixed(1)} ft</option>)}</select></label>)}</>}</details>
 <details open><summary>4. Artistic Depth Layers</summary><label>Water <select value={project.shoreline.waterMode??'primary'} onChange={e=>patch({shoreline:{...project.shoreline,waterMode:e.target.value as 'all'|'primary'}})}><option value="primary">Primary Water Body</option><option value="all">All Water</option></select></label><label>Preset <select value={project.shoreline.preset} onChange={e=>{const preset=e.target.value as ArtisticDepthPresetName;patch({shoreline:{...project.shoreline,preset,...(preset==='custom'?{}:{artisticOffsetsNormalized:[...ARTISTIC_DEPTH_PRESETS[preset].normalizedOffsets]})}})}}>{['xfine','fine','narrow','normal','wide','custom'].map(value=><option value={value} key={value}>{value==='xfine'?'XFine':value[0].toUpperCase()+value.slice(1)}</option>)}</select></label><small>Offsets are normalized design units, not surveyed depths.</small><label>Minimum area mm² <input type="number" min="0" step="1" value={project.shoreline.minWaterAreaMm2??1} onChange={e=>patch({shoreline:{...project.shoreline,minWaterAreaMm2:Math.max(0,+e.target.value)}})}/></label>{project.shoreline.enabledLayers.map((v,i)=><label key={i}><input type="checkbox" checked={v} onChange={e=>{const a=[...project.shoreline.enabledLayers];a[i]=e.target.checked;patch({shoreline:{...project.shoreline,enabledLayers:a}})}}/> {i===0?'Land':i===6?'Base':`Layer ${i+1}`}</label>)}</details>
 <details open><summary>5. Roads</summary><select value={project.roads.mode} onChange={e=>patch({roads:{...project.roads,mode:e.target.value as any}})}><option value="all">All</option><option value="main">Main</option><option value="off">Off</option></select></details>
 <details open><summary>8. Compass</summary><select value={project.compass.position} onChange={e=>patch({compass:{...project.compass,position:e.target.value as any}})}>{['top-left','top-right','bottom-left','bottom-right','custom','off'].map(x=><option key={x}>{x}</option>)}</select></details>{sections.map((s,i)=><details key={s}><summary>{[3,6,7,9,10][i]}. {s}</summary><small>Scene setting foundation is active.</small></details>)}
 <details open><summary>11. Export</summary><select value={project.exportSettings.layout} onChange={e=>patch({exportSettings:{...project.exportSettings,layout:e.target.value as any}})}><option value="production">Production Sheet</option><option value="registered">Registered Layers</option><option value="individual">Individual SVG files</option></select><button onClick={onGenerate}>Generate scene</button><button onClick={onExport}>Export SVG</button></details><div className="diagnostics"><b>{status}</b><span>Water polygons: {counts.water}</span><span>Road features: {counts.roads}</span><span>Named roads: {counts.namedRoads}</span><span>Places: {counts.places}</span></div></aside>}
