import {describe,expect,it,vi} from 'vitest';
import {automaticThresholds,importDepthRegionGeoJson,normalizeDepth} from '../../src/bathymetry/model';
import {BathymetryResolver,MemoryBathymetryCache} from '../../src/bathymetry/resolver';
import {WisconsinDnrProvider} from '../../src/bathymetry/providers';
import {buildScene} from '../../src/export/buildScene';
import {caldronFallsFeatures,caldronFallsProject} from '../fixtures/caldronFalls';
const rectangle=(depth:number,delta:number,extra:any={})=>({type:'Feature',properties:{depth,depth_unit:'ft'},geometry:{type:'Polygon',coordinates:[[[-88.21-delta,45.37-delta],[-88.21+delta,45.37-delta],[-88.21+delta,45.37+delta],[-88.21-delta,45.37+delta],[-88.21-delta,45.37-delta]]]},...extra});
const imported=importDepthRegionGeoJson({type:'FeatureCollection',features:[rectangle(5,.025),rectangle(15,.015),rectangle(30,.007)]},'caldron-digitized.geojson');
describe('bathymetry architecture',()=>{
 it('normalizes depth units and source metadata into serializable meters',()=>{expect(normalizeDepth(40,'ft')).toBeCloseTo(12.192);expect(imported.contours.map(c=>c.depthMeters)).toEqual([1.524,4.572,9.144]);expect(JSON.parse(JSON.stringify(imported))).toEqual(imported);expect(imported.source.notForNavigation).toBe(true)});
 it('selects deterministic supported automatic thresholds',()=>expect(automaticThresholds(imported.contours,2)).toEqual([1.524,9.144]));
 it('discovers Wisconsin waterbody identity through the official hydro service without claiming scanned maps are vectors',async()=>{const fetcher=vi.fn().mockResolvedValue({ok:true,json:async()=>({features:[{attributes:{WATERBODY_NAME:'Caldron Falls Reservoir',WATERBODY_WBIC:545400}}]})}),provider=new WisconsinDnrProvider(fetcher as any),result=await provider.resolve({longitude:-88.23,latitude:45.35});expect(result).toMatchObject({provider:'wisconsin-dnr',status:'unsupported',waterbodyId:'545400'});expect(result.message).toContain('no verified georeferenced depth polygons');expect(fetcher).toHaveBeenCalledOnce()});
 it('caches stable provider resolution by provider and geographic area',async()=>{const provider={id:'test',label:'Test',resolve:vi.fn().mockResolvedValue({provider:'user',status:'unsupported',message:'none'})},resolver=new BathymetryResolver([provider],new MemoryBathymetryCache()),query={longitude:1,latitude:2};await resolver.resolve(query);await resolver.resolve(query);expect(provider.resolve).toHaveBeenCalledOnce()});
 it('builds true depth panels from real depth-valued regions without decorative erosion',()=>{const project={...caldronFallsProject,bathymetry:{mode:'true-bathymetry' as const,provider:'user' as const,datasetId:imported.source.datasetId,status:'available' as const,selection:'automatic' as const,thresholdsMeters:[],dataset:imported}},scene=buildScene(project,caldronFallsFeatures),areas=scene.geometryMetrics!.openingAreasMm2;expect(scene.depthMode).toBe('true-bathymetry');expect(scene.bathymetrySource).toEqual(imported.source);expect(scene.layers.slice(1,4).map(layer=>layer.depthMeters)).toEqual([1.524,4.572,9.144]);expect(areas[1]).toBeLessThan(areas[0]);expect(areas[2]).toBeLessThan(areas[1]);expect(areas[3]).toBeLessThan(areas[2]);expect(scene.layers.every(layer=>layer.shapes.every(shape=>shape.kind==='rect'||!/NaN|Infinity/.test(shape.d!)))).toBe(true)});
 it('keeps decorative mode independent and refuses fake true depth',()=>{expect(()=>buildScene({...caldronFallsProject,bathymetry:{...caldronFallsProject.bathymetry,mode:'true-bathymetry',dataset:undefined}},caldronFallsFeatures)).toThrow('no verified depth-valued dataset');expect(buildScene(caldronFallsProject,caldronFallsFeatures).depthMode).toBe('decorative-offsets')});
});
