import {describe,expect,it} from 'vitest';
import {buildScene} from '../../src/export/buildScene';
import {scenePreviewSvg} from '../../src/export/svg/previewSvg';
import {caldronFallsFeatures,caldronFallsProject} from '../fixtures/caldronFalls';
const scene=buildScene(caldronFallsProject,caldronFallsFeatures);
const documentFor=(mode:'individual'|'composite'|'exploded',selected=0)=>new DOMParser().parseFromString(scenePreviewSvg(scene,mode,selected),'image/svg+xml');
describe('physical panel previews',()=>{
 it('renders exactly one complete filled panel in Individual mode',()=>{const doc=documentFor('individual',1),panels=doc.querySelectorAll('[data-preview-panel]');expect(panels).toHaveLength(1);expect(panels[0].getAttribute('data-preview-panel')).toBe('layer-depth-2');expect(panels[0].getAttribute('fill')).not.toBe('none');expect(panels[0].querySelector('path[fill-rule="evenodd"]')).toBeTruthy()});
 it('stacks filled complete panels from Base through Land in Composite mode without contour strokes',()=>{const doc=documentFor('composite'),panels=[...doc.querySelectorAll('[data-preview-panel]')];expect(panels).toHaveLength(scene.layers.length);expect(panels[0].getAttribute('data-preview-panel')).toBe('layer-base');expect(panels.at(-1)?.getAttribute('data-preview-panel')).toBe('layer-land');expect(panels.every(panel=>panel.getAttribute('fill')!=='none'&&panel.getAttribute('stroke')==='none')).toBe(true)});
 it('orders labeled complete panels Base-to-Land in a diagnostic grid',()=>{const doc=documentFor('exploded'),items=[...doc.querySelectorAll('[data-exploded-item]')],panels=[...doc.querySelectorAll('[data-preview-panel]')];expect(panels).toHaveLength(scene.layers.length);expect(items.map(item=>item.getAttribute('data-exploded-item'))).toEqual(['layer-base','layer-depth-4','layer-depth-3','layer-depth-2','layer-land']);expect(items.map(item=>item.getAttribute('transform'))).toEqual(['translate(0 0)','translate(365.6 0)','translate(731.2 0)','translate(0 301.4)','translate(365.6 301.4)']);expect(items.map(item=>item.querySelector('text')?.textContent)).toEqual(['BASE / BACKER','ARTISTIC DEPTH 3 · 20 UNITS','ARTISTIC DEPTH 2 · 9 UNITS','ARTISTIC DEPTH 1 · 3 UNITS','LAND / TOP'])});
 it('renders roads and compass only with the Land panel',()=>{const land=documentFor('individual',0),intermediate=documentFor('individual',1),base=documentFor('individual',scene.layers.length-1);expect(land.querySelectorAll('path[fill="none"]')).not.toHaveLength(0);expect(intermediate.querySelectorAll('path[fill="none"]')).toHaveLength(0);expect(base.querySelectorAll('path[fill="none"]')).toHaveLength(0)});
});
